//! Energy dispersal (ES 201 980 §7.2.2): the FAC/SDC/MSC bit stream is XORed with a
//! PRBS generated by x⁹ + x⁵ + 1, register preset to all ones. The very strongly
//! protected part of a hierarchical MSC frame uses an independently restarted
//! sequence. Scrambling is its own inverse.

/// XOR `bits` (one bit per byte, values 0/1) with the DRM PRBS in place. The first
/// `vspp_len` bits use one PRBS instance, the rest a fresh one.
pub fn apply(bits: &mut [u8], vspp_len: usize) {
    let (vspp, rest) = bits.split_at_mut(vspp_len.min(bits.len()));
    scramble(vspp);
    scramble(rest);
}

fn scramble(bits: &mut [u8]) {
    let mut reg: u32 = 0x1FF;
    for b in bits {
        // Taps at x⁹ and x⁵: register bits 8 and 4 (bit 0 = most recent output).
        let prbs = ((reg >> 4) ^ (reg >> 8)) & 1;
        reg = ((reg << 1) | prbs) & 0x1FF;
        *b ^= prbs as u8;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn prbs_starts_with_spec_sequence() {
        // ES 201 980 §7.2.2: first 16 bits with an all-ones preset are 0000 0111 1011 1110.
        let mut bits = vec![0u8; 16];
        apply(&mut bits, 0);
        assert_eq!(bits, [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0]);
    }
}
