#!/usr/bin/env python3
"""Generate the DRM AAC audio fixture (`tests/fixtures/drm/aac_sine_24k.{drm,ga}`).

The DRM AAC access unit re-serialiser (drm_aac_reserialize.py) converts a plain
MPEG-4 GA AAC-LC access unit into DRM syntax (VCB11 section data + HCR spectral
data + aac_crc_bits). This tool drives it over a run of ONLY_LONG frames and emits
two fixtures:

  * `*.drm` — the re-serialised DRM access units, concatenated (one per frame).
  * `*.ga`  — the original GA access units, concatenated, as the lossless reference.

Provenance
----------
The GA access units are produced by the Fraunhofer FDK AAC encoder built with the
DecDRM 960-sample patch (AAC-LC 24 kHz mono, 64 kbit/s CBR, 960-sample granule, a
1 kHz sine). The encoder is external (FDK licence); the committed fixture is data.

Regeneration
------------
1. Build the 960-sample-patched FDK encoder (see DecDRM `crates/decdrm-fdk-sys/build.rs`):
   apply the `AACENC_GRANULE_LENGTH=960` patches to `libAACenc/src/aacenc_lib.cpp`,
   `aacenc.cpp` and `psy_configuration.cpp`, then `cmake` + `make`.
2. Encode >= 4 frames of the 1 kHz sine (frames 0..2 are LONG_START/SHORT/LONG_STOP,
   from frame 3 on the signal is ONLY_LONG).
3. Run this script over the raw access units.
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from drm_aac_reserialize import BitReader, parse_frame, reserialize_drm, skip_fil_elements  # noqa: E402


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("ga_dir", help="directory of raw GA AAC access units (one per file)")
    ap.add_argument("out", help="output base path, e.g. tests/fixtures/drm/aac_sine_24k")
    ap.add_argument("--rate", type=int, default=24000, help="core sample rate (24 kHz)")
    ap.add_argument("--label", default="AAC 24kHz mono sine", help="fixture description")
    args = ap.parse_args()

    paths = sorted(glob.glob(os.path.join(args.ga_dir, "*.bin")))
    if not paths:
        print(f"no *.bin access units in {args.ga_dir}", file=sys.stderr)
        return 2

    drm_parts, ga_parts, sizes, kept = [], [], [], 0
    for p in paths:
        data = open(p, "rb").read()
        br = BitReader(data)
        skip_fil_elements(br)
        frame = data[br.pos >> 3:]
        # Peek window_sequence: id(3) tag(4) global_gain(8) ics_reserved(1) ws(2).
        peek = BitReader(frame)
        peek.read(3); peek.read(4); peek.read(8); peek.read(1)
        ws = peek.read(2)
        if ws != 0:
            continue  # LONG_START/SHORT/LONG_STOP not handled by the re-serialiser
        out = parse_frame(frame)
        drm = reserialize_drm(frame, out)
        blob = bytes(int(drm[i:i + 8].ljust(8, "0"), 2) for i in range(0, len(drm), 8))
        drm_parts.append(blob)
        ga_parts.append(frame)
        sizes.append(len(blob))
        kept += 1

    if kept < 2:
        print(f"only {kept} ONLY_LONG frames; need >= 2 to pass the decoder priming delay",
              file=sys.stderr)
        return 3

    with open(args.out + ".drm", "wb") as f:
        f.write(b"".join(drm_parts))
    with open(args.out + ".ga", "wb") as f:
        f.write(b"".join(ga_parts))

    meta = {
        "note": "DRM AAC audio fixture (data, not source). Generated by tools/gen_drm_aac_fixture.py "
                "from FDK-AAC (960-sample patch) GA access units re-serialised to DRM syntax.",
        "label": args.label,
        "codec": "AAC-LC (no SBR)",
        "sample_rate_hz": args.rate,
        "channels": 1,
        "granule_samples": 960,
        "bitrate_kbps": 64,
        "frames": kept,
        "drm_frame_bytes": sizes,
        "ga_frame_bytes": [len(g) for g in ga_parts],
        "type9_bytes": [3, 0],  # AAC 24 kHz, no SBR, mono
        "asc_bytes": [0x13, 0x0C],  # AAC-LC 24 kHz mono, 960-sample
        "verification": "native fdK-AAC TT_DRM decode of the .drm frames equals the TT_MP4_RAW decode of "
                        "the .ga frames bit-for-bit (mismatches=0) and is non-silent.",
    }
    with open(args.out + ".json", "w") as f:
        json.dump(meta, f, indent=2)
        f.write("\n")

    print(f"{kept} frames -> {args.out}.drm ({len(b''.join(drm_parts))} B), "
          f"{args.out}.ga ({len(b''.join(ga_parts))} B)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
