#!/usr/bin/env python3
"""Generate the golden binary-frame fixtures shared by the Python and TypeScript tests.

The fixtures are produced by the *production* encoders, so they cannot drift from the
wire format without a test failing:

  - Python: ``tests/test_frame_fixtures.py`` re-encodes the same values and asserts the
    committed bytes are identical (a format change must be accompanied by new fixtures).
  - TypeScript: ``frontend/modern/src/__tests__/frames.test.ts`` decodes the committed
    bytes and asserts every field against ``manifest.json`` (including the VSAD cloud, its
    ideal grid and the positional measurement block).
  - ``None`` in a manifest scalar means "not measured in this tier" and is written as NaN.

Usage:  python3 tools/gen_frame_fixtures.py [--check]
        --check  fail when the files on disk differ from what the code would produce
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from web_sa.measurements.framer import (  # noqa: E402
    encode_audio,
    encode_freq,
    encode_powr,
    encode_rta,
    encode_vsa,
)

OUT = ROOT / 'tests' / 'fixtures' / 'frames'

FREQ = {
    'version': 7,
    'points': 8,
    'sweep_ms': 12.5,
    'freq': [9.9e8 + i * 2.5e5 for i in range(8)],
}
POWR = {
    'version': 7,
    'points': 8,
    'sweep_ms': 12.5,
    'power': [-91.25, -88.5, -21.75, -20.0, -63.5, -95.25, -99.0, -100.5],
}
RTA = {
    'version': 3,
    'points': 6,
    'wf_len': 4,
    'max_density': 1234,
    'start_hz': 9.734375e8,
    'stop_hz': 1.0265625e9,
    'freq': [9.75e8 + i * 1.0e7 for i in range(6)],
    'spec': [-101.5, -98.25, -18.75, -19.5, -97.0, -103.25],
    'wf_row': [0, 17, 4096, 65535],
}
AUDIO = {
    'seq': 42,
    'rate': 48000,
    'pcm': [0, 1, -1, 32767, -32768, 1234, -4321, 99],
}
VSA = {
    'version': 5,
    'kind': 'constellation',
    'scalars': {'symbol_rate_hz': 244140.625, 'cfo_hz': 12.5, 'timing_samples': 0.25,
                'evm_percent': None, 'snr_db': 21.5},
    'cloud': [[0.0007, 0.0007], [-0.0007, 0.0007], [-0.0007, -0.0007], [0.0007, -0.0007]],
    'ideal': [[0.001, 0.001], [-0.001, 0.001], [-0.001, -0.001], [0.001, -0.001]],
    'measurements': {'mean_dbm': -25.25, 'duty': 1.0, 'samples': 262144.0},
}


def build():
    """Return {filename: bytes} plus the manifest dict, using the production encoders."""
    freq = np.asarray(FREQ['freq'], dtype=np.float64)
    power = np.asarray(POWR['power'], dtype=np.float32)
    rta_freq = np.asarray(RTA['freq'], dtype=np.float64)
    rta_spec = np.asarray(RTA['spec'], dtype=np.float32)
    rta_row = np.asarray(RTA['wf_row'], dtype=np.uint16)
    pcm = np.asarray(AUDIO['pcm'], dtype=np.int16)
    vsa_cloud = np.asarray(VSA['cloud'], dtype=np.float32)
    vsa_ideal = np.asarray(VSA['ideal'], dtype=np.float32)
    vsa_scalars = tuple(np.nan if VSA['scalars'][key] is None else VSA['scalars'][key]
                        for key in ('symbol_rate_hz', 'cfo_hz', 'timing_samples',
                                    'evm_percent', 'snr_db'))

    files = {
        'freq.bin': encode_freq(FREQ['version'], freq, FREQ['sweep_ms']),
        'powr.bin': encode_powr(POWR['version'], power, POWR['sweep_ms']),
        'rta.bin': encode_rta(RTA['version'], rta_freq, rta_spec, rta_row,
                               RTA['max_density'], RTA['start_hz'], RTA['stop_hz']),
        'audio.bin': encode_audio(AUDIO['seq'], AUDIO['rate'], pcm),
        'vsa.bin': encode_vsa(VSA['version'], VSA['kind'], vsa_cloud, ideal=vsa_ideal,
                              scalars=vsa_scalars, measurements=VSA['measurements']),
    }
    manifest = {
        'note': 'Generated by tools/gen_frame_fixtures.py from the production encoders. '
                'Do not edit by hand.',
        'freq': {**FREQ, 'file': 'freq.bin'},
        'powr': {**POWR, 'file': 'powr.bin'},
        'rta': {**RTA, 'file': 'rta.bin'},
        'audio': {**AUDIO, 'file': 'audio.bin'},
        'vsa': {**VSA, 'file': 'vsa.bin'},
    }
    return files, manifest


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true',
                        help='verify the committed fixtures instead of writing them')
    args = parser.parse_args()

    files, manifest = build()
    manifest_bytes = json.dumps(manifest, indent=1, sort_keys=True).encode() + b'\n'

    if args.check:
        problems = []
        for name, data in files.items():
            path = OUT / name
            if not path.exists() or path.read_bytes() != data:
                problems.append(name)
        if not (OUT / 'manifest.json').exists() or (OUT / 'manifest.json').read_bytes() != manifest_bytes:
            problems.append('manifest.json')
        if problems:
            print('fixture drift:', ', '.join(problems), file=sys.stderr)
            print('run: python3 tools/gen_frame_fixtures.py', file=sys.stderr)
            return 1
        print('fixtures OK')
        return 0

    OUT.mkdir(parents=True, exist_ok=True)
    for name, data in files.items():
        (OUT / name).write_bytes(data)
        print(f'{name}: {len(data)} bytes')
    (OUT / 'manifest.json').write_bytes(manifest_bytes)
    print('manifest.json')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
