#!/usr/bin/env python3
"""Port the FT8 protocol tables from ft8_lib into this repository.

The tables are the FT8 specification's constants (Costas sync pattern, Gray map, the
LDPC(174,91) parity-check matrix and CRC-14 polynomial). They are *facts of the protocol*, and the
permissively licensed implementation they are taken from is recorded here rather than transcribed by
hand — hand-copying 83x12 bytes is how a decoder ends up subtly non-interoperable.

    Source:  ft8_lib, https://github.com/kgoba/ft8_lib
    Licence: MIT (Copyright (c) 2018 Kārlis Goba)
    Files:   ft8/constants.c, ft8/constants.h

The generated files are committed (so a build never needs the upstream checkout):

    wasm/src/digital/ft8/tables.rs        the Rust decoder's constants
    tests/fixtures/ft8/tables.json        the same values for the Python fixture generator

Usage:
    git clone --depth 1 https://github.com/kgoba/ft8_lib /tmp/ft8_lib
    python3 tools/port_ft8_tables.py [/tmp/ft8_lib]
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = Path(sys.argv[1] if len(sys.argv) > 1 else '/tmp/ft8_lib')
RUST_OUT = ROOT / 'wasm' / 'src' / 'digital' / 'ft8' / 'tables.rs'
JSON_OUT = ROOT / 'tests' / 'fixtures' / 'ft8' / 'tables.json'

HEADER = """//! FT8 protocol constants.
//!
//! GENERATED by `tools/port_ft8_tables.py` from ft8_lib (MIT, Copyright (c) 2018 Kārlis Goba,
//! https://github.com/kgoba/ft8_lib) — do not edit by hand, and see the provenance table in
//! `docs/*/ARCHITECTURE.md`. These are the FT8 specification's constants: the Costas sync pattern,
//! the Gray map, the CRC-14 polynomial and the LDPC(174,91) matrices.

"""


def numbers(text: str) -> list[int]:
    return [int(value, 0) for value in re.findall(r'0[xX][0-9a-fA-F]+|\d+', text)]


def array_body(source: str, name: str) -> str:
    """Text between the braces of `name = { ... }` (handles nested braces)."""
    start = source.index(name)
    start = source.index('{', start)
    depth = 0
    for index in range(start, len(source)):
        if source[index] == '{':
            depth += 1
        elif source[index] == '}':
            depth -= 1
            if depth == 0:
                return source[start + 1:index]
    raise SystemExit(f'unterminated array for {name}')


def rows(body: str) -> list[list[int]]:
    return [numbers(row) for row in re.findall(r'\{([^{}]*)\}', body)]


def main() -> int:
    constants_c = (SOURCE / 'ft8' / 'constants.c').read_text()
    constants_h = (SOURCE / 'ft8' / 'constants.h').read_text()
    if 'MIT' not in (SOURCE / 'LICENSE').read_text():
        raise SystemExit(f'{SOURCE}/LICENSE is not the MIT licence this port assumes')

    costas = numbers(array_body(constants_c, 'kFT8_Costas_pattern'))
    gray = numbers(array_body(constants_c, 'kFT8_Gray_map'))
    generator = rows(array_body(constants_c, 'kFTX_LDPC_generator'))
    nm = rows(array_body(constants_c, 'kFTX_LDPC_Nm'))
    mn = rows(array_body(constants_c, 'kFTX_LDPC_Mn'))
    num_rows = numbers(array_body(constants_c, 'kFTX_LDPC_Num_rows'))
    polynomial = numbers(re.search(r'FT8_CRC_POLYNOMIAL \(\(uint16_t\)(0[xX][0-9a-fA-F]+)u?\)',
                                  constants_h).group(1))[0]
    width = int(re.search(r'FT8_CRC_WIDTH\s+\((\d+)\)', constants_h).group(1))

    assert len(costas) == 7 and len(gray) == 8
    assert len(generator) == 83 and all(len(row) == 12 for row in generator)
    assert len(nm) == 83 and all(len(row) == 7 for row in nm)
    assert len(mn) == 174 and all(len(row) == 3 for row in mn)
    assert len(num_rows) == 83
    # `Nm` rows are zero-padded to 7 entries; `Num_rows` gives the real length, which is exactly how
    # the decoder iterates them. Only the non-zero entries are node indices.
    assert all(0 <= value <= 174 for row in nm for value in row)
    for row, count in zip(nm, num_rows, strict=True):
        assert all(1 <= row[index] <= 174 for index in range(count)), f'bad Nm row {row} ({count})'
        assert all(value == 0 for value in row[count:]), f'non-zero padding in Nm row {row}'
    assert all(1 <= value <= 83 for row in mn for value in row)

    def rust_u8(name: str, values: list[int]) -> str:
        return f'pub const {name}: [u8; {len(values)}] = [{", ".join(str(v) for v in values)}];\n'

    def rust_table(name: str, table: list[list[int]]) -> str:
        inner = ',\n    '.join('[' + ', '.join(str(v) for v in row) + ']' for row in table)
        return (f'pub const {name}: [[u8; {len(table[0])}]; {len(table)}] = [\n    {inner},\n];\n')

    rust = HEADER
    rust += rust_u8('COSTAS', costas)
    rust += rust_u8('GRAY', gray)
    rust += f'pub const CRC_POLYNOMIAL: u16 = 0x{polynomial:04x};\npub const CRC_WIDTH: u32 = {width};\n'
    rust += rust_u8('LDPC_NUM_ROWS', num_rows)
    rust += rust_table('LDPC_GENERATOR', generator)
    rust += rust_table('LDPC_NM', nm)
    rust += rust_table('LDPC_MN', mn)
    rust += 'pub const LDPC_N: usize = 174;\npub const LDPC_K: usize = 91;\npub const LDPC_M: usize = 83;\n'
    rust += 'pub const NUM_SYMBOLS: usize = 79;\npub const NUM_DATA_SYMBOLS: usize = 58;\n'
    rust += 'pub const SYNC_LENGTH: usize = 7;\npub const SYNC_OFFSET: usize = 36;\n'
    rust += 'pub const SYMBOL_PERIOD_S: f64 = 0.160;\npub const TONE_SPACING_HZ: f64 = 6.25;\n'
    rust += 'pub const SLOT_SECONDS: f64 = 15.0;\n'

    RUST_OUT.parent.mkdir(parents=True, exist_ok=True)
    RUST_OUT.write_text(rust)
    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(json.dumps({
        'note': 'FT8 protocol constants ported from ft8_lib (MIT, Copyright (c) 2018 Kārlis Goba) '
                'by tools/port_ft8_tables.py. Do not edit by hand.',
        'costas': costas,
        'gray': gray,
        'crc_polynomial': polynomial,
        'crc_width': width,
        'ldpc_generator': generator,
        'ldpc_nm': nm,
        'ldpc_mn': mn,
        'ldpc_num_rows': num_rows,
    }, indent=1, sort_keys=True) + '\n')
    print(f'wrote {RUST_OUT.relative_to(ROOT)} ({len(rust)} bytes)')
    print(f'wrote {JSON_OUT.relative_to(ROOT)}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
