// Callsign → country/region via the AD1C cty.dat DXCC table (data in ctyData.ts, generated by
// tools/gen_cty.py). Exact override first, then longest prefix; `/P` suffixes are stripped.
import { CTY_ENTITIES, CTY_EXACT, CTY_PREFIXES, CTY_ZH } from './ctyData';

export interface CtyCountry {
	/** DXCC entity name (English). */
	name: string;
	/** Localized display name (falls back to the English name). */
	zh: string;
}

export function countryFor(callsign: string): CtyCountry | null {
	const raw = callsign.trim();
	if (!raw) return null;
	const upper = raw.toUpperCase();
	const idx = CTY_EXACT[raw.toLowerCase()] ?? CTY_PREFIXES[longestPrefix(upper)];
	if (idx === undefined) return null;
	return { name: CTY_ENTITIES[idx], zh: CTY_ZH[idx] ?? CTY_ENTITIES[idx] };
}

/** The base callsign before any `/` suffix, then the longest defined prefix of it. */
function longestPrefix(call: string): string {
	const base = call.split('/')[0];
	for (let length = base.length; length >= 1; length--) {
		const prefix = base.slice(0, length);
		if (prefix in CTY_PREFIXES) return prefix;
	}
	return '';
}
